---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: project-template-base

namespace: project-template

commonLabels:
  app.kubernetes.io/name: project-template
  app.kubernetes.io/managed-by: kustomize

resources:
- ../../manifests/namespace.yaml
- ../../manifests/rbac.yaml
- ../../manifests/configmap.yaml
- ../../manifests/secrets.yaml
- ../../manifests/flask-backend/deployment.yaml
- ../../manifests/flask-backend/service.yaml
- ../../manifests/go-backend/deployment.yaml
- ../../manifests/go-backend/service.yaml
- ../../manifests/webui/deployment.yaml
- ../../manifests/webui/service.yaml
- ../../manifests/webui/ingress.yaml
