---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend
  namespace: project-template
  labels:
    app.kubernetes.io/name: flask-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flask-backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
