apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webui.fullname" . }}-config
  labels:
    {{- include "webui.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  {{- toYaml .Values.configMapData | nindent 2 }}
