apiVersion: v2
name: repo-worker
description: Multi-architecture Helm and Docker Repository Service
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - docker
  - registry
  - helm
  - repository
  - oci
maintainers:
  - name: Penguin Tech Inc
    email: support@penguintech.io
dependencies:
  - name: minio
    version: "1.0.0"
    repository: "file://../minio"
    condition: minio.enabled
