---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: project-template-staging

namespace: project-template-staging

namePrefix: staging-

commonLabels:
  environment: staging

bases:
- ../../base

replicas:
- name: flask-backend
  count: 2
- name: go-backend
  count: 2
- name: webui
  count: 1

configMapGenerator:
- name: project-template-config
  behavior: merge
  literals:
  - LOG_LEVEL=INFO
  - RELEASE_MODE=false

secretGenerator:
- name: project-template-secrets
  behavior: merge
  literals:
  - DB_USER=staginguser
  - DB_PASS=stagingpass
  - SECRET_KEY=stagingsecretkey
  - SECURITY_PASSWORD_SALT=stagingsalt
  - LICENSE_KEY=PENG-STAG-XXXX-XXXX-XXXX-ABCD
  - REDIS_PASSWORD=staginredis
